### ISSUE TITLE
 Add "Blue School Headline" field to School model

### ISSUE THREAD

**Issue by Justinnkar** [Candid-Maven/education-directory-net-cms#45]
**Description:**
In the School model, add a new CharField named blue_school_headline.

**Steps to Reproduce:**

1. Navigate to the School model.
2. Add a new CharField named blue_school_headline with a max length of 255.

**Expected Outcome:**
A new field named blue_school_headline should be present in the School model.

**Comment by csaument** [comment]
Incorporated into #48
